name: event_bus_riverpod
description: "Type-safe event bus with Riverpod integration for Flutter."
version: 3.2.6
repository: https://github.com/livegnik97/event_bus_riverpod.git
homepage: https://github.com/livegnik97/event_bus_riverpod

environment:
  sdk: ^3.11.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.0.0

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter: null

# flutter pub publish --dry-run
# flutter pub publish

