name: event_bus_riverpod
description: "A type-safe, Riverpod-integrated event bus for Flutter. It allows you to emit and listen to events anywhere in your app using Riverpod's dependency injection and lifecycle management."
version: 1.2.1
repository: https://github.com/livegnik97/event_bus_riverpod.git
homepage: https://github.com/livegnik97/event_bus_riverpod

environment:
  sdk: ^3.11.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.3.2

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter: null

# flutter pub publish --dry-run
# flutter pub publish

